name: integration for run test

on:
  pull_request:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu_lastest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: yarn install
      - run: yarn test
      - run: yarn run build
